### ISSUE TITLE
Pitch-step going from start-up to normal operation

### ISSUE THREAD

**Issue by jantoreh** [DTUWindEnergy/BasicDTUController#14]
Experiencing a dramatic change in pitch reference, which is not handled well by my simulation program. The issue seems to be that the pitch rate is not limited when going from controlstatus=-1 to 0. See attach figure, for two time-steps when the controller status is switched.
<img width="471" alt="screen shot 2017-03-29 at 12 27 06" src="https://cloud.githubusercontent.com/assets/22801649/24450695/197e37e4-147c-11e7-9d25-609ce75bf717.png">

**Comment by jantoreh** [comment]
Proposed solution in pull request

**Comment by profhansen** [comment]
Assume that it has been resolved by the approved pull request from @jantoreh
