### ISSUE TITLE
controller_input.txt   dq/dtheta value

### ISSUE THREAD

**Issue by christosgal** [DTUWindEnergy/BasicDTUController#9]
In the controller_input.txt file which is output from HAWCSTAB2 (see attached photo which is provided with the DTU 10MW rwt model  with some explanations) it is not clear in which point dq/dtheta is evaluated. I refer to the value in the 'PI pitch angle controller in region 3' part of the txt file. Is it at zero theta? If yes could it be written as dq/dtheta_zero which is more clear? 
same for the dq/domega in the 'Additional terms due to the Aerodynamic damping' part of the file.

![controller_input_quadratic_example](https://cloud.githubusercontent.com/assets/26140726/23508260/1fd35826-ff51-11e6-853e-ce121f276a8a.PNG)

**Comment by profhansen** [comment]
This is a HS2 issue and has to do with the steady state computation. I will close it from here.
